services:
  - type: web
    name: g2-proposals
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
